### ISSUE TITLE
matcher.isCurrent(item) doesn't work with extra params

### ISSUE THREAD

**Issue by exchentrix** [jbouzekri/ConfigKnpMenuBundle#14]
Hey,

thanks again for your great effort.

I noticed a strange behaviour when using the extra params in my menu. Here is my configuration:

```yaml
main_menu:
    childrenAttributes:
        class: nav-main
    tree:
        menu_1:
            label: Menu Item 1
            route: landing_index
            extras:
                icon: si-speedometer
        seperator:
            label: Seperator
            attributes:
                class: nav-main-heading
        menu_2:
            label: Menu Item 2
            route: site_foo
            extras:
                icon: si-layers
            children:
                menu_2_1:
                    label: Submenu Item 1
                    route: site_bar
```

My view script for the menu:

```twig
{% extends 'KnpMenuBundle::menu.html.twig' %}

{% block linkElement %}

    {% set toggle = item.hasChildren ? 'data-toggle="nav-submenu"' : null %}
    {% set classes = item.hasChildren ? ['nav-submenu'] : [] %}
    {% set classes = matcher.isCurrent(item) ? classes|merge(['active']) : classes %}

    <a class="{{ classes|join(' ') }}" href="{{ item.uri }}" {{ toggle|raw }}>
        {% if item.level == 1 %}
            <i class="si {{ item.getExtra('icon') }}"></i>
        {% endif %}
        <span class="sidebar-mini-hide">{{ block('label') }}</span>
    </a>
{% endblock %}
```

From the twig template:

```twig
<div class="side-content">
    {{ knp_menu_render('main_menu', {
        'template': 'SiteBundle:Menu:main_menu.html.twig',
        'currentClass': null,
        'ancestorClass' : 'open',
        'firstClass' : null,
        'lastClass' : null})
    }}
</div>
```

The matcher is working as expected. If I request /bar:

![menu1](https://cloud.githubusercontent.com/assets/1130714/18034628/e9821de4-6d41-11e6-8307-ba7b901cf5c6.png)

Everything is fine. Now when I set an extra param on the last node, the matcher is not working as expected:

```yaml
main_menu:
    childrenAttributes:
        class: nav-main
    tree:
        menu_1:
            label: Menu Item 1
            route: landing_index
            extras:
                icon: si-speedometer
        seperator:
            label: Seperator
            attributes:
                class: nav-main-heading
        menu_2:
            label: Menu Item 2
            route: site_foo
            extras:
                icon: si-layers
            children:
                menu_2_1:
                    label: Submenu Item 1
                    route: site_bar
                    extras:
                        translation_domain: menu # added this
```

And the result für /bar:

![menu2](https://cloud.githubusercontent.com/assets/1130714/18034652/5d2ec832-6d42-11e6-8089-91af0f6dc8a2.png)

The matcher also returns the incorrect result if Menu_Item_1 is current. It's also grey instead of white when I request the node.

The appropriate a-tag has no active class on it. Do you know, what could be the problem here? 

Maybe it has nothing to do with your bundle.

Best,
Christian
